import '@reactil/tailwind-preset';
import { ModeToggle, ThemeProvider } from '@reactil/components';

export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body>
          <header>
            <ModeToggle />
          </header>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
